language: c

compiler: gcc

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - python3
      - nasm

before_install:
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python3 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install nasm    ; fi

install:
  - git clone git://git.cacharle.xyz/libasm ../libasm

script:
  - make bonus
